baseURL = "https://www.natuerlich-andrea.de/"
languageCode = "de-de"
title = "Natürlich! Andrea."
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "2021 Andrea Immerheiser-Jahr"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description =""
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Andrea"
  thumbnail = "/images/authorthumb.jpg"
  description = "Die Kreative hinter dieser Website"

[params.index]
  picture = "/images/author.jpg"
  titlepicture = "/images/spirale.png"
  title = "Andrea"
  subtitle = "Die Kreative hinter dieser Website"
  mdtext = '''
Ich liebe die Natur, die Tiere und Menschen, die Kreativität und die Vielseitigkeit in meinem Leben und Tun.
Ich bin kein Spezialist, kein Tiefseetaucher. Ich habe nicht ein Thema, ein Fachgebiet, dem ich komplett bis auf den Grund gehen will.
Manchmal reichen mir bereits ein paar Informationen, ein paar “Spritzer” eines Themas und ich springe von Pfütze zu Pfütze.
Ist eine Sache für mich größer und weiter, eher wie ein Teich oder See, gehe ich mal nur mit den Füßen, mal bis zum Bauch ins Wasser.
Manchmal springe ich kopfüber in etwas Neues hinein, ohne zu ahnen, was mich erwartet.
Gleicht mein Interesse einem Fluss, lasse ich mich eine zeitlang treiben und schwimme auch mal mit aller Kraft gegen den Strom.
Manchmal bleibe ich lange im weiten Meer, ziehe in aller Ruhe meine Kreise und tauche hier und da tiefer ein.
Doch eines ist sicher, ich werde wieder auftauchen und weiterziehen, wenn mich ein neues Gewässer fasziniert.

Warum ich hier also schreibe, hat mehrere Gründe. 

Zum Einen glaube ich, dass es viele von Euch gibt, denen es ähnlich geht. 
Die nicht glücklich sind damit, sich auf nur eine Sache zu konzentrieren, immer an einem Ziel dranzubleiben und dabei die bunte Welt rechts und links aus den Augen zu verlieren.
Zum Anderen habe ich einen riesigen Fundus an inspirierenden Ideen, Texten, Bildern gesammelt und es kommen täglich neue Dinge hinzu. 
Ich möchte all das mit Euch teilen, auf dass wir uns alle immer wieder gegenseitig inspirieren und unsere Welt immer farbenfroher und bunter wird.

Wie schön, das Du hier bist!

Schau Dich in Ruhe um und tauche ein, in die Inspirationen, die Dich gerade ansprechen.

Andrea
'''
  alertbar = false

[params.social]
  instagram = "natuerlich.andrea"

## Main Menu
[[menu.main]]
    name = "Kreatives"
    weight = 100
    identifier = "creative"
    url = "/creative"
[[menu.main]]
    name = "Alltägliches"
    weight = 110
    identifier = "homemade"
    url = "/homemade"
[[menu.main]]
    name = "Zeichnungen"
    weight = 120
    identifier = "sketches"
    url = "/sketches"
[[menu.main]]
    name = "Inspirationen"
    weight = 120
    identifier = "inspirations"
    url = "/inspirations"
[[menu.main]]
    name = "Andrea"
    identifier = "about"
    weight = 200
    url = "/about"
[[menu.main]]
    name = "Impressum/Datenschutz"
    identifier = "imprint"
    weight = 200
    url = "/imprint"
