backend:
  name: git-gateway
  branch: master
media_folder: static/images/blog
public_folder: /images/blog
site_url: https://natuerlich-andrea.de
logo_url: https://natuerlich-andrea.de/images/logo.png
locale: 'de'
collections:
  - name: creative
    label: Kreatives
    folder: content/creative
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Datum', name: 'date', widget: 'datetime', required: true }
      - { label: 'Entwurf', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Bild', name: 'image', widget: 'image', required: false }
      - { label: 'Text', name: 'body', widget: 'markdown',  required: true}
  - name: homemade
    label: Alltägliches
    folder: content/homemade
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Datum', name: 'date', widget: 'datetime', required: true }
      - { label: 'Entwurf', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Bild', name: 'image', widget: 'image', required: false }
      - { label: 'Text', name: 'body', widget: 'markdown',  required: true}
  - name: inspirations
    label: Inspirationen
    folder: content/inspirations
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Datum', name: 'date', widget: 'datetime', required: true }
      - { label: 'Entwurf', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Bild', name: 'image', widget: 'image', required: false }
      - { label: 'Text', name: 'body', widget: 'markdown',  required: true}
  - name: sketches
    label: Zeichnungen
    folder: content/sketches
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Datum', name: 'date', widget: 'datetime', required: true }
      - { label: 'Entwurf', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Bild', name: 'image', widget: 'image', required: false }
      - { label: 'Text', name: 'body', widget: 'markdown',  required: true}
